// Mapa de nombres de restaurantes a sus ciudades correspondientes
export const restaurantCities = {
  'Tiramisú': 'Las Condes, Chile',
  'Hard Rock Cafe': 'Santiago, Providencia, Chile',
  'Los Vikingos Restaurant': 'Santiago, Chile',
  'Vapiano pasta y pizza Pedro de Valdivia': 'Providencia, Chile',
  'Giratorio': 'Providencia, Chile',
  'Le Bistrot de Gaetan': 'Providencia, Chile',
  'Fuente Alemana': 'Providencia, Chile',
  'Baco': 'Providencia, Chile',
  'Restaurante il Cuore | Fábrica de pastas': 'Santiago, Chile',
  'Tacu Tacu Restaurante - Providencia': 'Providencia, Chile',
  'Chipe Libre - República Independiente del Pisco': 'Santiago, Chile',
  'Restaurant BADA': 'Santiago, Chile',
  'El Huerto': 'Providencia, Chile',
  'Bocanáriz': 'Santiago, Chile',
  'Nusantara Indonesia Comida Tipica de Indonesia': 'Providencia, Chile',
  'Restaurant Puerto Esmeralda San pablo': 'Santiago, Chile',
  'Elkika Ilmenau': 'Providencia, Chile',
  'Ramen Ryoma Providencia': 'Providencia, Chile',
  'Swagat Comida India': 'Santiago, Chile',
  'Everyday Sushi Restaurant': 'Santiago, Chile',
  'Restaurant Bidasoa': 'Santiago, Vitacura, Chile',
  'Ramblas Bar': 'Providencia, Chile',
  'La Cabrera Chile': 'Vitacura, Chile',
  'Castillo Forestal': 'Santiago, Chile',
  'Carnal Prime Steakhouse': 'Vitacura, Chile',
  'La Cabrera Chile Isidora': 'Las Condes, Chile',
  'Korean Restaurant Sukine': 'Recoleta, Chile',
  'Restaurant Sicilia': 'Santiago, Chile',
  'Restaurant Pez de Oro II': 'Santiago, Chile',
  'Morera Casa Bar': 'Vitacura, Chile',
  'Cupbab Express': 'Providencia, Chile',
  'Teke Factory - Fábrica de Tequeños': 'Providencia, Chile',
  'Dama Blanca Restaurant': 'Santiago, Chile',
  'Don Carlos': 'Las Condes, Chile',
  'Domani Pizzeria Napolitana & Bar - Tobalaba': 'Santiago, Providencia, Chile',
  'Buriana': 'Vitacura, Chile',
  'Restaurante Malandros': 'Providencia, Chile',
  'Restaurant Ai-Wha': 'Santiago, Chile',
  'Galpón Alonso': 'Vitacura, Chile',
  'Restaurante Ecuatoriano Don Bolo': 'Santiago, Chile',
  'Restaurant Harissa': 'Recoleta, Chile',
  'Restaurante Hansoban': 'Recoleta, Chile',
  'De Patio Restaurante': 'Vitacura, Chile',
  'La Fabrica Craft Beer & Restaurant': 'Vitacura, Chile',
  'La Loncheria': 'Santiago, Chile',
  'Santako': 'Providencia, Chile',
  'Restaurant los Chillanejos': 'Recoleta, Chile',
  'La Bifería': 'Providencia, Santiago, Chile',
  'Woking Restaurant': 'Las Condes, Chile',
  'Restaurant Miraolas': 'Santiago, Vitacura, Chile',
  'Seviza Restaurant': 'Santiago, Chile',
  'Starnberg': 'Vitacura, Chile',
  'La Fonda Paisa Restaurante': 'Santiago, Chile',
  'La Flaca, Cocinería Chilena': 'Las Condes, Chile',
  'Romaria': 'Vitacura, Chile',
  'Aligot restaurant': 'Las Condes, Chile',
  'Eladio Restaurant Providencia': 'Providencia, Chile',
  'Tio Tomate Mañio': 'Vitacura, Chile',
  'Pasta Pazza - Ristorante Terraza & Delivery': 'Providencia, Chile',
  'Restaurant China': 'Santiago, Chile',
  'Oporto Steak Bar': 'Santiago, Las Condes, Chile',
  'Sicily Pizza, Gelato e Caffe': 'Vitacura, Chile',
  'Restaurant "Jiang Nan"': 'Santiago, Chile',
  'La Dicha Restaurant': 'Vitacura, Chile',
  '99 Restaurante': 'Vitacura, Chile',
  'Soler Las Condes': 'Las Condes, Chile',
  'Momotaro Los Leones': 'Providencia, Chile',
  'Casa las Cujas': 'Vitacura, Chile',
  'GREZ restaurante': 'Providencia, Chile',
  'Fukasawa by Marcos Baeza': 'Vitacura, Chile',
  'Restaurant "You Yi"': 'Santiago, Chile',
  'Restaurant Bristol': 'Santiago, Chile',
  'Margó Parque Arauco': 'Las Condes, Chile',
  'Ana María Restaurant': 'Santiago, Chile',
  'The Singular Restaurant': 'Santiago, Chile',
  'Da Renzo': 'Providencia, Chile',
  'Confitería Torres': 'Las Condes, Chile',
  'Restaurant Alcobri': 'Recoleta, Chile',
  'Encuentros Restaurant - Bar': 'Providencia, Chile',
  'Hijo del Sol Las condes': 'Las Condes, Chile',
  'Restaurant Sabores de Mita': 'Providencia, Chile',
  'Rivoli': 'Providencia, Chile',
  'Gioia Gourmet Restaurant': 'Santiago, Chile',
  'Curry & Kabab Indian Restaurant': 'Providencia, Chile',
  'Palacio Danubio Azul': 'Las Condes, Chile',
  'Dominó': 'Providencia, Chile',
  'soul of india': 'Vitacura, Chile',
  'Restaurant Long Hui': 'Santiago, Chile',
  'Restaurant Pantaleón (Teatinos)': 'Santiago, Chile',
  'DGANG Club Restaurant': 'Las Condes, Chile',
  'Restaurant Oriental': 'Providencia, Chile',
  'Olam Restaurante': 'Santiago, Las Condes, Chile',
  'Restaurant Jabri': 'Recoleta, Chile',
  'Pizzario': 'Las Condes, Chile',
  'Restaurant Pavo Real': 'Santiago, Chile',
  'Restaurant Peking': 'Santiago, Chile',
  'Matsuri': 'Las Condes, Chile',
  'Kintaro Ramen Bar': 'Vitacura, Chile',
  'Karai by Mitsuharu': 'Las Condes, Chile',
  'Restaurant Kwan Ming': 'Santiago, Chile',
  'Restaurant Punto 8': 'Santiago, Chile',
  'Luvi restaurante': 'Las Condes, Chile',
  'Diablo Vino y Fuego Restaurante': 'Las Condes, Chile',
  'Selfish Chile El Golf': 'Las Condes, Chile',
  'Restaurant Donde JC': 'Santiago, Chile',
  'Restaurant Y Marisqueria Clarita': 'Santiago, Chile',
  'Restaurant Domenica': 'Providencia, Chile',
  'Osishi restaurant': 'Providencia, Chile',
  'Restaurante Hao Hwa': 'Santiago, Chile',
  'El Granjero Restaurant': 'Santiago, Chile',
  'Squella Restaurant': 'Santiago, Chile',
  'Holy Moly Tobalaba': 'Providencia, Chile',
  'Utopía Restobar': 'Santiago, Chile',
  'QB Restaurant': 'Las Condes, Chile',
  'Restaurant Limoncello': 'Santiago, Chile',
  'Restaurant el Super Gordo (Bandera)': 'Santiago, Chile',
  'Rugendas Restaurant': 'Las Condes, Chile',
  'Restaurant "Sabores de mi Perú"': 'Santiago, Chile',
  'Huascaran Restaurant': 'Providencia, Chile',
  'Siraj Shawarma - Providencia': 'Providencia, Chile',
  'Biwon': 'Providencia, Chile',
  'Restaurante Pavo Real': 'Providencia, Chile',
  'Restaurant Flor de Fa (Pesa y Paga)': 'Santiago, Chile',
  'Restaurant "Vamos Chile"': 'Santiago, Chile',
  'Atahualpa. Restaurant Peruano': 'Recoleta, Chile',
  'Restaurant Tentacion': 'Santiago, Chile',
  'Restaurante Club Providencia': 'Providencia, Chile',
  'Restaurante Peking': 'Santiago, Chile',
  'Del Valle Gourmet Restaurant-Café': 'Santiago, Chile',
  'Karlita restaurant': 'Providencia, Chile',
  'La Diana Restaurante': 'Santiago, Chile',
  'Sol Restaurant': 'Providencia, Chile',
  'Restaurant Fu Lin': 'Santiago, Chile',
  'Muu Steak - Isidora Goyenechea': 'Las Condes, Chile',
  'Restaurant Guo Fung Ltda.': 'Santiago, Chile',
  'Moloko': 'Providencia, Chile',
  'Ciro\'s Bar Restaurant': 'Santiago, Chile',
  'Tres Valles Restaurant Lastarria': 'Santiago, Chile',
  'Restaurant Cruz Coke 350': 'Santiago, Chile',
  'Restaurant Hon Loc': 'Providencia, Chile',
  'Córdova Restaurant': 'Vitacura, Chile',
  'Mesón Danés': 'Santiago, Chile',
  'Restaurant Miski Wasi': 'Santiago, Chile',
  'Restaurant Portada del Sol': 'Santiago, Chile',
  'Restaurant La Blanquita': 'Maipú, Santiago, Chile',
  'Otoshi Teppanyaki Bar and Restaurante': 'Las Condes, Chile',
  'Yokono Los Leones': 'Providencia, Chile',
  'Mexa': 'Las Condes, Chile',
  'Tante Marlene': 'Vitacura, Chile',
  'Menchoy Restaurant': 'Santiago, Chile',
  'Restaurant sabor oriental': 'Santiago, Chile',
  'Asia Sabrosa Restaurant': 'Santiago, Chile',
  'Restaurant "Sui - Hwa"': 'Santiago, Chile',
  'Restaurant Mitsuwa': 'Santiago, Chile',
  'Restaurant Xin Qing Fung': 'Santiago, Chile',
  'Al Jazeera Restaurant': 'Providencia, Chile',
  'Un Oasis Restaurant': 'Santiago, Chile',
  'Restaurant Azafran': 'Providencia, Chile',
  'Pub Restaurante Teclados': 'Vitacura, Chile',
  'Pub Restaurant La Casona De Catedral Limitada': 'Santiago, Chile',
  'Make Make Restaurant': 'Santiago, Chile',
  'Restaurante Enebro': 'Las Condes, Chile',
  'Amaranto Restaurant': 'Santiago, Chile',
  'Restaurant Alpamayo': 'Santiago, Chile',
  'Restaurante 18': 'Santiago, Chile',
  'Nuria Restaurant': 'Santiago, Chile',
  'Maru Restaurante': 'Las Condes, Chile',
  'Hansik Market & Restaurant': 'Providencia, Chile',
  'Hotel Boutique Holitel': 'Providencia, Chile',
  'La Provincia Restaurant': 'Las Condes, Chile',
  'Restaurant Los Rubies': 'Santiago, Chile',
  'Catae Restaurant': 'Santiago, Vitacura, Chile',
  'Restaurante Wan He': 'Providencia, Chile',
  'Restaurant YOU CHEN': 'Santiago, Chile',
  'Brüder Lange Bar Restaurant': 'Santiago, Chile',
  'Restaurante y Pollo a las Brasas TAPUY': 'Providencia, Chile',
  'Shinsei (Renaissance)': 'Vitacura, Chile',
  'Vietnam Discovery Restaurant': 'Vitacura, Chile',
  'Restaurant Club Radical': 'Santiago, Chile',
  'Restaurant Mar De Lupe': 'Santiago, Chile',
  'Restaurant Cafetería la India': 'Santiago, Chile',
  'Restaurant Flor de Retama internacional': 'Santiago, Chile',
  'Restaurant la aceituna': 'Providencia, Chile',
  'Yokono Lyon': 'Providencia, Chile',
  'Restaurant Bar Toronto': 'Las Condes, Chile',
  'Do Sushi Restaurante': 'Providencia, Chile',
  'Restaurant Faisan D\'Or': 'Santiago, Chile',
  'Barra La Java': 'Vitacura, Chile',
  'Restaurante Ju Xian Lou': 'Las Condes, Santiago, Chile',
  'Restaurant Las Delicias': 'Santiago, Chile',
  'Restaurant Tung Fong': 'Providencia, Chile',
  'Restaurant Chino Venezolano': 'Santiago, Chile',
  'Brasero Lounge': 'Las Condes, Chile',
  'Barra Chalaca - Vivo Panoramico': 'Providencia, Chile',
  'Restaurant AlpaQuitay': 'Santiago, Chile',
  'El Japonés - Vivo Panoramico': 'Providencia, Chile'
};

// Función para obtener la ciudad de un restaurante por su nombre
export const getRestaurantCity = (restaurantName) => {
  return restaurantCities[restaurantName] || 'Ubicación no disponible';
};
