export const initialSiteConfig = {
        homePageHeroImage: 'https://images.unsplash.com/photo-1691727477684-3e244369d5f1',
        homePageHeroAlt: 'Esquiadores descendo uma montanha nevada nos Andes chilenos sob um céu azul brilhante',
        logoUrl: '' 
    };

    export const initialTours = [
       {
            id: 'atacama-stars',
            name: 'San Pedro de Atacama: Deserto e Estrelas',
            nameLine1: 'San Pedro de Atacama:',
            nameLine2: 'Deserto e Estrelas',
            duration: '4 Dias / 3 Noites',
            pricePerAdult: 3750, 
            pricePerChild: 2750, 
            location: 'San Pedro de Atacama, Chile',
            description: 'Descubra a magia do deserto mais árido do mundo. Maravilhe-se com paisagens que parecem de outro planeta, como o Vale da Lua e o Vale da Morte. Visite os Gêiseres del Tatio ao amanhecer, relaxe nas Termas de Puritama e explore as impressionantes lagoas altiplânicas Miscanti e Miñiques. À noite, desfrute de um dos céus mais limpos do planeta com um tour astronômico.',
            gallery: ['atacama-valley-moon-pano', 'geysers-el-tatio-sunrise', 'atacama-lagunas-altiplanicas', 'atacama-starry-night'],
            itinerary: [
                'Dia 1: Chegada em Calama (CJC), traslado para San Pedro. Tarde: Vale da Lua e Vale da Morte ao pôr do sol.',
                'Dia 2: Manhã: Lagoas Altiplânicas (Miscanti e Miñiques) e Salar de Atacama (Lagoa Chaxa). Tarde livre.',
                'Dia 3: Madrugada: Gêiseres del Tatio. Manhã: Relaxamento nas Termas de Puritama (opcional). Noite: Tour Astronômico.',
                'Dia 4: Manhã livre. Traslado para o aeroporto de Calama (CJC).',
            ],
            includes: ['Traslados aeroporto Calama - San Pedro (ida e volta)', '3 noites de hospedagem em San Pedro com café da manhã', 'Excursões mencionadas com guia (Vale da Lua, Lagoas Altiplânicas, Gêiseres del Tatio)', 'Entradas para parques e reservas mencionadas', 'Tour Astronômico'],
            excludes: ['Voos de/para Calama (CJC)', 'Almoços e jantares', 'Entrada para as Termas de Puritama (se opcional)', 'Seguro de viagem', 'Gorjetas'],
            availableDates: [],
            offers: [],
            image: 'atacama-valley-moon-wide',
            isVisible: true,
            startTime: '',
            endTime: '',
            checklist: '',
            termsAndConditions: '',
       },
       {
            id: 'torres-paine-w',
            name: 'Trekking W em Torres del Paine',
            nameLine1: 'Trekking W em',
            nameLine2: 'Torres del Paine',
            duration: '5 Dias / 4 Noites',
            pricePerAdult: 5500, 
            pricePerChild: 4500,
            location: 'Parque Nacional Torres del Paine, Chile',
            description: 'Embarque na aventura de trekking mais icônica da Patagônia. A "W" leva você através de paisagens arrebatadoras: o mirante Base Torres, o Vale do Francês com suas geleiras suspensas e a impressionante Geleira Grey. Uma experiência inesquecível para amantes da natureza e do senderismo.',
            gallery: ['torres-paine-base-view', 'valle-frances-lookout', 'glaciar-grey-viewpoint', 'patagonia-trekking-group'],
            itinerary: [
                'Dia 1: Traslado para Torres del Paine. Trekking para Base Torres. Noite no Refúgio Chileno ou Central.',
                'Dia 2: Trekking margeando o Lago Nordenskjöld. Noite no Refúgio Los Cuernos ou Francês.',
                'Dia 3: Trekking ao Vale do Francês (Mirante Britânico opcional). Noite no Refúgio Paine Grande.',
                'Dia 4: Trekking em direção à Geleira Grey. Opcional: caminhada no gelo ou caiaque. Noite no Refúgio Grey.',
                'Dia 5: Manhã livre ou trekking pontes suspensas. Navegação Lago Pehoé. Traslado de volta para Puerto Natales.',
            ],
            includes: ['Traslados de/para Puerto Natales', '4 noites de hospedagem em refúgios de montanha (dormitório compartilhado)', 'Pensão completa nos refúgios (café da manhã, lanche de trilha, jantar)', 'Entrada para o Parque Nacional Torres del Paine', 'Catamarã Lago Pehoé'],
            excludes: ['Voos de/para Puerto Natales ou Punta Arenas', 'Equipamento de trekking pessoal (saco de dormir, mochila, etc.)', 'Guia (disponível com custo adicional)', 'Atividades opcionais (caiaque, caminhada no gelo)', 'Seguro de viagem', 'Gorjetas'],
            availableDates: [],
            offers: [],
             image: 'torres-del-paine-base-trek',
             isVisible: true,
             startTime: '08:00',
             endTime: '18:00',
             checklist: 'Levar protetor solar\nUsar calçado de trekking\nAgasalho corta-vento\nGarrafa de água reutilizável',
             termsAndConditions: 'A reserva deve ser confirmada com 48 horas de antecedência. Cancelamentos com menos de 24 horas não terão reembolso.',
       },
       {
            id: 'easter-island-mystery',
            name: 'Ilha de Páscoa: Mistérios Ancestrais',
            nameLine1: 'Ilha de Páscoa:',
            nameLine2: 'Mistérios Ancestrais',
            duration: '5 Dias / 4 Noites',
            pricePerAdult: 4750, 
            pricePerChild: 3750, 
            location: 'Ilha de Páscoa (Rapa Nui), Chile',
            description: 'Viaje para a ilha mais remota do planeta e desvende os segredos da cultura Rapa Nui. Visite os impressionantes Ahu com seus Moai, explore o vulcão Rano Raraku (a pedreira dos Moai) e Rano Kau com sua aldeia cerimonial Orongo. Relaxe na praia de Anakena e mergulhe em uma cultura única.',
            gallery: ['moais-ahu-tongariki-easter-island', 'rano-raraku-moai-quarry-easter-island', 'anakena-beach-easter-island-moai', 'orongo-village-easter-island-ocean'],
            itinerary: [
                 'Dia 1: Chegada na Ilha de Páscoa (IPC), recepção com colar de flores. Traslado para o hotel.',
                 'Dia 2: Tour de dia inteiro: Ahu Akahanga, Rano Raraku, Ahu Tongariki, Te Pito Kura, Praia Anakena.',
                 'Dia 3: Tour de meio dia: Vulcão Rano Kau, Aldeia Cerimonial Orongo, Ahu Vinapu.',
                 'Dia 4: Tour de meio dia: Ahu Akivi (os 7 exploradores), Pedreira Puna Pau, Caverna Ana Te Pahu.',
                 'Dia 5: Manhã livre. Traslado para o aeroporto (IPC).',
            ],
            includes: ['Traslados aeroporto - hotel (ida e volta)', '4 noites de hospedagem em Hanga Roa com café da manhã', 'Excursões mencionadas com guia local', 'Recepção com colar de flores'],
            excludes: ['Voos de/para Ilha de Páscoa (IPC)', 'Entrada para o Parque Nacional Rapa Nui (comprada na chegada)', 'Almoços e jantares', 'Seguro de viagem', 'Gorjetas'],
            availableDates: [],
            offers: [],
            image: 'easter-island-moai-group',
            isVisible: true,
            startTime: '',
            endTime: '',
            checklist: 'Levar chapéu ou boné\nRespeitar os sítios arqueológicos (não tocar nos Moai)\nDinheiro em espécie para artesanato local',
            termsAndConditions: 'Parque Nacional Rapa Nui requer ingresso separado, pago localmente.',
       },
       {
             id: 'santiago-wine',
             name: 'Santiago e Vinhedos Próximos: Descobrindo Sabores Chilenos',
             nameLine1: 'Santiago e Vinhedos Próximos:',
             nameLine2: 'Descobrindo Sabores Chilenos',
             duration: '3 Dias / 2 Noites',
             pricePerAdult: 2250, 
             pricePerChild: 1500,
             location: 'Santiago e Vale do Maipo/Casablanca, Chile',
             description: 'Descubra a vibrante capital do Chile, Santiago, com seus bairros históricos e modernos. Desfrute de um tour pela cidade e depois explore um dos vales vinícolas próximos (Maipo ou Casablanca) para degustar excelentes vinhos chilenos diretamente nas vinícolas.',
             gallery: ['santiago-plaza-armas', 'palacio-la-moneda-santiago', 'casablanca-valley-vineyard', 'wine-tasting-chile'],
             itinerary: [
                 'Dia 1: Chegada em Santiago (SCL). Traslado para o hotel. Tarde livre.',
                 'Dia 2: Manhã: City tour por Santiago (Centro histórico, Palácio de la Moneda, Cerro Santa Lucía). Tarde: Tour a vinícola no Vale do Maipo ou Casablanca com degustação.',
                 'Dia 3: Manhã livre. Traslado para o aeroporto (SCL).',
             ],
             includes: ['Traslados aeroporto - hotel (ida e volta)', '2 noites de hospedagem em Santiago com café da manhã', 'City tour em Santiago', 'Tour a vinícola com transporte e degustação'],
             excludes: ['Voos de/para Santiago (SCL)', 'Almoços e jantares', 'Seguro de viagem', 'Gorjetas'],
             availableDates: [],
             offers: [],
             image: 'santiago-chile-skyline-andes',
             isVisible: true,
             startTime: '09:00',
             endTime: '17:00',
             checklist: 'Câmera fotográfica para registrar os vinhedos\nRoupa confortável',
             termsAndConditions: 'Degustações sujeitas a disponibilidade da vinícola. Menores de idade não podem degustar bebidas alcoólicas.',
        },
        { 
            id: 'valparaiso-colors', 
            name: 'Valparaíso: Morros e Cores, Arte Urbana e História Viva', 
            nameLine1: 'Valparaíso: Morros e Cores,',
            nameLine2: 'Arte Urbana e História Viva',
            duration: 'Dia Inteiro', 
            pricePerAdult: 450, 
            pricePerChild: 300, 
            location: 'Valparaíso, Chile', 
            description: 'Percorra os morros coloridos, elevadores e arte de rua de Valparaíso, cidade Patrimônio da Humanidade.', 
            image: 'valparaiso-colorful-houses-hill', 
            itinerary: ['Tour guiado a pé pelos Cerros Alegre e Concepción', 'Visita a La Sebastiana (casa de Neruda, opcional)', 'Passeio em elevador patrimonial'], 
            includes: ['Transporte de Santiago (opcional)', 'Guia bilíngue'], 
            excludes: ['Almoço', 'Entradas (La Sebastiana, elevadores)'], 
            availableDates: [], 
            offers: [],
            isVisible: true,
            startTime: '10:00',
            endTime: '18:00',
            checklist: 'Calçado confortável para caminhar em morros\nDinheiro para elevadores e souvenirs',
            termsAndConditions: 'Passeio envolve bastante caminhada em terreno irregular.'
        },
        { 
            id: 'chiloe-magic', 
            name: 'Chiloé: Igrejas Patrimoniais e Lendas Encantadas da Ilha', 
            nameLine1: 'Chiloé: Igrejas Patrimoniais e',
            nameLine2: 'Lendas Encantadas da Ilha',
            duration: '4 Dias', 
            pricePerAdult: 3400, 
            pricePerChild: 2400, 
            location: 'Ilha Grande de Chiloé, Chile', 
            description: 'Descubra a cultura única, palafitas e igrejas de madeira Patrimônio da Humanidade na mágica ilha de Chiloé.', 
            image: 'chiloe-palafitos-castro', 
            itinerary: ['Visita a Castro e suas palafitas', 'Rota das Igrejas (Dalcahue, Achao)', 'Parque Nacional Chiloé', 'Mercado de Dalcahue'], 
            includes: ['Traslados', '3 noites de hospedagem com café da manhã', 'Excursões mencionadas', 'Guia local'], 
            excludes: ['Voos para Castro ou Puerto Montt', 'Refeições', 'Entradas'], 
            availableDates: [], 
            offers: [],
            isVisible: false, 
            startTime: '',
            endTime: '',
            checklist: 'Capa de chuva (o clima é instável)\nAdaptador de tomada universal',
            termsAndConditions: 'Algumas igrejas podem ter horários de visita restritos.'
        },
        { 
            id: 'lake-district-volcanoes', 
            name: 'Região dos Lagos: Vulcões Imponentes e Termas Relaxantes', 
            nameLine1: 'Região dos Lagos: Vulcões',
            nameLine2: 'Imponentes e Termas Relaxantes',
            duration: '6 Dias', 
            pricePerAdult: 4600, 
            pricePerChild: 3250, 
            location: 'Puerto Varas / Puerto Montt, Chile', 
            description: 'Paisagens verdes, vulcões imponentes (Osorno, Calbuco), lagos cristalinos (Llanquihue) e termas relaxantes.', 
            image: 'puerto-varas-lake-volcano-osorno', 
            itinerary: ['Puerto Varas', 'Saltos del Petrohué', 'Vulcão Osorno', 'Frutillar', 'Termas', 'Ilha de Chiloé (opcional)'], 
            includes: ['Traslados', '5 noites de hospedagem com café da manhã', 'Excursões base', 'Guia'], 
            excludes: ['Voos para Puerto Montt', 'Refeições', 'Entradas', 'Termas', 'Excursões opcionais'], 
            availableDates: [], 
            offers: [],
            isVisible: true,
            startTime: '',
            endTime: '',
            checklist: 'Roupa de banho para as termas\nRepelente de insetos',
            termsAndConditions: 'Entrada para as termas não incluída, pode ser paga no local.'
        },
        { 
            id: 'carretera-austral-north', 
            name: 'Carretera Austral Norte: Aventura Pura na Patagônia Chilena', 
            nameLine1: 'Carretera Austral Norte:',
            nameLine2: 'Aventura Pura na Patagônia Chilena',
            duration: '8 Dias', 
            pricePerAdult: 7500, 
            pricePerChild: 6000, 
            location: 'Puerto Montt a Coyhaique, Chile', 
            description: 'Explore fiordes, geleiras suspensas (Queulat), florestas virgens e povoados pitorescos na Patagônia norte.', 
            image: 'carretera-austral-queulat-hanging-glacier', 
            itinerary: ['Parque Pumalín', 'Chaitén', 'Parque Nacional Queulat', 'Puyuhuapi', 'Coyhaique'], 
            includes: ['Transporte 4x4 ou van', '7 noites de hospedagem (hosterías/cabanas)', 'Cafés da manhã', 'Alguns jantares', 'Guia motorista', 'Travessias de balsa'], 
            excludes: ['Voos', 'Refeições não especificadas', 'Entradas para parques', 'Atividades opcionais'], 
            availableDates: [], 
            offers: [],
            isVisible: true,
            startTime: '',
            endTime: '',
            checklist: 'Roupas para clima variado (camadas)\nBinóculos para observação da fauna',
            termsAndConditions: 'Roteiro sujeito a alterações devido a condições climáticas ou de estrada.'
        },
    ];